### ISSUE TITLE
Add file sharing option

### ISSUE THREAD

**Issue by phy25** [easy4u/writerplus-community#10]
The current shareing function shares content by text. Is it possible to share the whole file (like `Writer.md`) to 3rd apps? Sometimes this is more convenient to transfer content to the PC.

**Comment by easy4u** [comment]
The share file feature is supported in the new version v1.45, which supports share file as: .txt, .md, .png, .html. More file format will be supported in the future version.  You can try it: https://www.dropbox.com/s/ccoqjqagkqn0mp6/WriterP-play-xxhdpi-20161123-v1.45-RELEASE.apk?dl=0

**Comment by phy25** [comment]
😃 Thanks! I see that update on the Play store beta channel. Glad to see the share prompt in the material-design style 👍
