### ISSUE TITLE
Unable to revert strike-through text

### ISSUE THREAD

**Issue by ruslangaripov** [easy4u/writerplus-community#11]
I can't revert strike-through text to normal one. The following are steps to reproduce the bug:

1. Create a new markdown file with some text inside.

![wp01](https://cloud.githubusercontent.com/assets/16339987/21875889/1b31d724-d8a1-11e6-9e08-f493ac171eef.png)

2. Make the text strike-through with `~~`.

![wp02](https://cloud.githubusercontent.com/assets/16339987/21875909/365ce91c-d8a1-11e6-977f-51f0576235e0.png)

3. Now remove both `~~`.

![wp03](https://cloud.githubusercontent.com/assets/16339987/21875923/4cd4e49c-d8a1-11e6-9249-d0f59a6a52a4.png)

As you can see, the text remains strike-through.

I'm using WriterPlus v1.45.

**Comment by nusushika** [comment]
When adding ~~ to the text, you can insert two spaces before and after the text. Instead of this: 

~~test~~

 type like this: 

~~ test ~~

Hopefully it would help.

**Comment by ruslangaripov** [comment]
@nusushika The problem is not how to **not** to strike text through. The problem is how to remove the line after one has removed both `~~`.

**Comment by nusushika** [comment]
Please see the attached image.

![screenshot_20170409-235632](https://cloud.githubusercontent.com/assets/10937027/24838770/6d829ee4-1d81-11e7-8cde-fced15f067e1.png)

**Comment by ruslangaripov** [comment]
I see :-) But that's *workaround*, not a fix :finnadie:
