### ISSUE TITLE
Dark mode for AMOLED displays

### ISSUE THREAD

**Issue by sojusnik** [easy4u/writerplus-community#3]
Nowadays more and more smartphones have AMOLED screens and therefore it would be very eye- and energy-friendly to have an AMOLED mode (with a completely black background) in your great writer.

**Comment by easy4u** [comment]
Got it. Will add an option to support AMOLED mode.

**Comment by sojusnik** [comment]
Any ETA on this one?

**Comment by easy4u** [comment]
Sorry, I am busy with the sync feature. I can send you a beta version this
evening Beijing time.

THANKS,
Eric

2016-06-02 5:17 GMT+08:00 sojusnik <notifications@github.com>:

**Comment by easy4u** [comment]
Please try the attached beta version. Please tell me your comments. THANKS.

Eric

2016-06-07 14:01 GMT+08:00 EASY4U <easy4u.co@gmail.com>:

**Comment by sojusnik** [comment]
Didn't get any attachment. Try to add it in GitHub, not sending per E-Mail.

**Comment by easy4u** [comment]
Sorry. please download [WriterP-play-xxhdpi-20160607-v1.40-amoled-RELEASE.apk](https://github.com/easy4u/writerplus-community/blob/master/WriterP-play-xxhdpi-20160607-v1.40-amoled-RELEASE.apk)

**Comment by sojusnik** [comment]
Looks good, but it would be much better, if the top notification bar could be transparent and would vanish, if a real immersive mode will be implemented, like proposed [here](https://github.com/easy4u/writerplus-community/issues/4).

**Comment by sojusnik** [comment]
I'm closing this, since the dark mode is already decent implemented in the new version.
