### ISSUE TITLE
Sync with Google Drive

### ISSUE THREAD

**Issue by sojusnik** [easy4u/writerplus-community#6]
Since every Android user normally also has a Google Drive account, (auto)syncing to Google Drive would be an additional measure to keep your texts safely backuped.

**Comment by easy4u** [comment]
The feature is under development.

**Comment by sojusnik** [comment]
Nice to hear. Do you have an ETA?

**Comment by easy4u** [comment]
May be early of July.

**Comment by easy4u** [comment]
WriterSync (https://play.google.com/store/apps/details?id=co.easy4u.writer.sync) has been released. You can use it to sync files in WriterPlus app.
