### ISSUE TITLE
European time format

### ISSUE THREAD

**Issue by sojusnik** [easy4u/writerplus-community#7]
Instead of the AM/PM time format in the status bar (where the actual letter count and date is shown in grey), European users should see the date in an "European" format like 23:14 or 07:12.

**Comment by easy4u** [comment]
I have already made some modification on the time format. Have you tried the new version?

**Comment by sojusnik** [comment]
Yes, it looks great now, thanks!

BTW, it would be really cool, if you could have a look on the [immersive mode](https://github.com/easy4u/writerplus-community/issues/4) issue, if time and resources permit it. Thanks in advance!
